package model.elements;

public enum GamePhase {
  USE_ITEM_BEFORE_ACTIVATE,
  ACTIVATE_PILE,
  ENGAGE_DICE,
  USE_ITEM_BEFORE_ENGAGE,
  USE_ITEM_BEFORE_ASSIGN,
  USE_ITEM_EFFECT,
  ASSIGN_DICE,
  RECOVER_DICE,
  THROW_ITEM,
  CLEAR
}
